version: "3.8"

services:
  db:
    image: postgres:15
    container_name: rd-filebot-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./data/backend
    container_name: rd-filebot-backend
    environment:
      - PORT=${PORT_BACKEND}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ./data:/app/data

      # 🟡 CHANGE THESE TO MATCH YOUR HOST PATHS:
      - /path/to/your/realdebrid:/rd:ro          # ← Required: Real-Debrid read-only mount
      - /path/to/your/movies:/movies             # ← Required: Destination folder for movies
      - /path/to/your/series:/series             # ← Required: Destination folder for series
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./data/frontend
    container_name: rd-filebot-frontend
    environment:
      - PORT=${PORT_FRONTEND}
    ports:
      - "${PORT_FRONTEND}:3000"
    depends_on:
      - backend
    restart: unless-stopped
